### ISSUE TITLE
[BUG] Wrench icon must be explicitly hovered to select

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#101]
Current styling makes the wrench icon look like one of the navbar elements, and its appearances changes on hover, but this entire element does not constitute a link, so the wrench has to be pixel-perfect selected in order to open. Suggest making the entire element a link

@Oricul

**Comment by Oricul** [comment]
I honestly had never noticed that. Just instinctively clicked the icon. However, it should be fixed in the above PR along with some styling changes to make it more similar to other icons.

**Comment by aclist** [comment]
It's pretty minor, just something that gives that extra "oomph" in terms of usability.
