### ISSUE TITLE
[FEAT] Add step, min, and max to 'number' input field

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#105]
@aclist maybe im wrong but is there no way to add steps for the number input within the manifest? for now i was just gonna add them using the dom but i thought maybe this would be good to have available. i didnt see anything for it in kes.user.js

_Originally posted by @minnieoo in https://github.com/aclist/kbin-kes/issues/85#issuecomment-1636180758_

**Comment by aclist** [comment]
Resolved by b7052af07bfd53bf9366fa2ca07e82dd4499d1ac

**Comment by minnieoo** [comment]
looking good! thanks for this :D
