### ISSUE TITLE
[BUG] Testing Branch: Something broke the wrench icon... Again...

### ISSUE THREAD

**Issue by Oricul** [aclist/kbin-kes#112]
**Describe the bug**
Update from testing branch now leaves the wrench lying on the floor on kbin instances that are in the 'main' branch. For kbin instances that are inbetween (or on dev) branches of kbin (like kbin.social), it's now right-aligned in it's div.

**To Reproduce**
1. Update kes-testing and clear local caches.
2. Reload your favorite kbin instance.

**Screenshots**
![kbin/main](https://files.catbox.moe/a4uhfe.png) ![kbin/develop](https://files.catbox.moe/ku5rx4.png)

**KES version:**
- 2.0.0-rc.33

**Extension and version:**
- Extension: TamperMonkey
- Version number: 4.19.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: LibreWolf (Firefox)
 - Browser version: 115.0.1-1

**Comment by aclist** [comment]
I did notice a few mods breaking due to some changed selectors, updated that accordingly.

But relatedly, there is a new notifier icon I added that may nudge the positioning of the wrench due to the use of the `fa-stack` class, so may need to normalize it further. Can you test this by manually editing the version number in the script to something that is not `2.0.0-rc.33`, reolading, and checking where the wrench and the exclamation point show up? Just to see if there is any other interaction going on here.

**Comment by Oricul** [comment]
This probably brings up a point though. We could probably use a RC branch that is separate from the testing branch.

**Comment by aclist** [comment]
Hmm, I see, so what is the proposed approach here as far as kbin is concerned? Should we just expect things on dev instances to take some time to smooth out before reaching mainline? Shouldn't we be targeting the stable instances mainly?

As far as branch logic, you think there should be a stable, a RC, and then a testing branch for elaboration of features/patches that are out-of-band, which then get merged into RC, tested, and finally to main?

**Comment by Oricul** [comment]
The problem with choosing a branch to support and a branch to not support is that _most_ instances run main, whereas the biggest ones run _develop_ or mostly-_develop_ branches.

And for the branch logic, that's my thinking. Having something marked as a release candidate break isn't ideal, you know? An RC branch could potentially be a protected branch that needs more than 1 reviewer so that it's probably reviewed and stable before going into main upon release.

**Comment by aclist** [comment]
Right. It seems a bit intractable and a maintainability nightmare until the upstream development stabilizes a bit. We can't be carrying around two versions of the codebase for changes that come up here and there, and it's tough that the instance are fragmented across both types, but it stands to reason. Can we try to enforce `!important` for this particular element?

Branch logic makes sense. Is the expectation that RC should target kbin main, though? If the biggest instances run develop, aren't they basically a petri dish as it is?

**Comment by Oricul** [comment]
I hate throwing around `!important` unless it's actually needed. Let me take a look at what you're trying to accomplish with the `!` icon and how it's built. I can almost guarantee that changing it's parent element to something like a `span` would fix problems, but want to verify first.

The fragmentation is actually from kbin's own setup guides. By default it tosses you into the develop branch, but if you want a stable environment, you have to checkout main instead. I only found out today that I was in develop when my entire server took a dump. 

For the RC, my best recommendation would be to target kbin.social. So it's a _not-quite-develop_ branch, but it just means that, at least for now, we support the develop branch. 

_P.S.,_ There's discussion on kbin's matrix about not changing classes willy-nilly in the future. Apparently the vote_up button had it's class removed and the vote_down button had it's class set to vote_up.

**Comment by aclist** [comment]
> I hate throwing around !important unless it's actually needed. Let me take a look at what you're trying to accomplish with the ! icon and how it's built. I can almost guarantee that changing it's parent element to something like a span would fix problems, but want to verify first.

Yes, please take a look. I agree. It actually is in a span tag, but maybe there is some CSS wizardry you can do here. If you could take a look at the https://github.com/aclist/kbin-kes/issues/61 while you are at it, that would be great. There are only four issues remaining in [this milestone](https://github.com/aclist/kbin-kes/milestone/3), with three of them merely being cosmetic annoyances, so I think the only thing that remains to be done here is freeze the version and stress test against all extensions again.

> For the RC, my best recommendation would be to target kbin.social. So it's a not-quite-develop branch, but it just means that, at least for now, we support the develop branch.

It makes sense, as this project essentially grew out of there.

> P.S., There's discussion on kbin's matrix about not changing classes willy-nilly in the future. Apparently the vote_up button had it's class removed and the vote_down button had it's class set to vote_up.

Good thing I have both disabled! That sounds more like a snafu than an intentional design choice, though.

**Comment by Oricul** [comment]
@aclist How about something like this?

![Update Example](https://files.catbox.moe/m69q6a.gif)

**Comment by aclist** [comment]
Hmm, any alternatives we can workshop? It's not bad, just didn't scream "updates available" to me, looks more like a fancy detail. Granted, the existence of anything here is going to signal something new happened, but would prefer something that just screams updates if possible.

**Comment by Oricul** [comment]
Such as? I changed it to this from "!" as it screamed error.

**Comment by aclist** [comment]
Hahaha. I don't disagree with that. I am thinking.

**Comment by Oricul** [comment]
I originally wanted to use the cloud up arrow, but it's too small.

![Cloud Example](https://files.catbox.moe/lvzz39.gif)

**Comment by aclist** [comment]
Right, I forgot for a moment this was a text string and not an icon. 

Some alternatives:
・ ----> This is pretty good and unobstrusive, just give it a color and you are good to go. Downside, it resembles a presence indicator.
![a](https://github.com/aclist/kbin-kes/assets/92275929/6aad15aa-99d9-4302-93d9-1ac84c1e9ea3)

⟳ -----> Fairly self explanatory and shouldn't be too small, I think I like this one best. Impossible to misunderstand.
![3](https://github.com/aclist/kbin-kes/assets/92275929/a0c2f721-e912-4bed-9eb1-f589d4062de6)

Another alternative is using fa icons and tweaking the size e.g. fa-xs, but you're right that most are going to be too busy/large.

**Comment by aclist** [comment]
I also think left hand side is better here, since the wrench itself is tilted up and to the right, so the eye naturally follows from the update icon to the wrench, rather than below, where it feels like they are fighting in opposite directions

**Comment by Oricul** [comment]
I'm actually using fa icons for this. Speaking to the wife, she also didn't like my first suggestion. The dot is like a notification or presence. The circle one you have there makes me think of reload or restart. 

Was workshopping with the wife, she tends to like this one the best out of what she's seen here:
![wife-suggestion](https://files.catbox.moe/kldeg2.gif)

**Comment by aclist** [comment]
That's not bad, it reminds me of ejecting a CD, though.

Hmm, yeah, fontawesome can be a bit limiting at times in that the same icons are used everywhere for specific services, but then when you need something that unambiguously stands for something, there isn't a good one.

There are a ton of possibilities in pure Unicode that aren't associated with specific brands/services. I'm thinking a stylized arrow would do the trick? Going to search for some.

**Comment by aclist** [comment]
Also wanted to add that the cloud icon is synonymous with "synch", rather than "download."

**Comment by Oricul** [comment]
The cloud at least had an up arrow, but made me think of upload. I've always seen up arrows for updates - nothing else really.

**Comment by Oricul** [comment]
For now, I'm going to open a PR. It can be changed to whatever later.

**Comment by aclist** [comment]
Yeah, do agree with up arrows being important here.

Feast your eyes on these:
1. Hmm, uncomfortably reminiscent of Reddit, maybe it's the thickness and color?
![a_007](https://github.com/aclist/kbin-kes/assets/92275929/210de09d-8d5d-4c83-8316-a96e4076a583)
2. Too fancy
![a_006](https://github.com/aclist/kbin-kes/assets/92275929/74106903-678a-4ed8-9fc7-9b71458028f4)
3. Nice and simple?
![a_004](https://github.com/aclist/kbin-kes/assets/92275929/c44be3af-4560-440b-9195-9ceb03c05a20)
4. This one isn't half bad. It's also a bit shorter than number 3 in height
![a_005](https://github.com/aclist/kbin-kes/assets/92275929/24672464-3126-41ec-8292-e7d19f4e592c)

**Comment by aclist** [comment]
> For now, I'm going to open a PR. It can be changed to whatever later.

Sure, thank you. The burning question is whether the arrow should be facing down or up. I tend to agree with you that down arrow implies, well, download, versus upload.

**Comment by Oricul** [comment]
Currently the color pulls form kbin's stylesheet. I'd be careful about using colors defined statically - potentially invisible if someone uses those colors in theme. As long as the structure stays the same, and the new CSS options around position and display stay the same, you can mostly do whatever with it.

**Comment by aclist** [comment]
> I'd be careful about using colors defined statically - potentially invisible if someone uses those colors in theme. 

Yes, agreed. I tend to use hi-vis colors when testing something. There might be a few areas where there is still something hardcoded. Come to think of it, the Transparent Mode border should be interpolated from `var(--kbin-success-color)` as well, thanks for the reminder.

**Comment by Oricul** [comment]
Uh-oh. What happened?

**Comment by aclist** [comment]
Take a look here, https://github.com/aclist/kbin-kes/pull/119/files#r1264554282, I added a comment on it. Looks like this PR was missing changes involving Transparent Mode, I didn't notice, and it got clobbered. Should be restored now. 

Is this the final placement you went with, or am I still missing some part of the stylesheet?

![a](https://github.com/aclist/kbin-kes/assets/92275929/caca5bbf-c74c-468b-bdd5-ee44f6ab6e08)

**Comment by Oricul** [comment]
You're definitely missing part of the stylesheet.

**Comment by aclist** [comment]
Looking perfect now. Do you think the icon should change color on hover?

**Comment by Oricul** [comment]
I did it to draw additional attention to it, like "hey I'm important", but ultimately as long as the user understands, it doesn't matter too much.

**Comment by aclist** [comment]
Let's keep the look for now, seems good. I just tend to think that once you dial in a UI, if you start changing cosmetic details  too much after the fact, users get frustrated because they are attached to something that feels familiar, so you should try to commit to one design and not commit the Apple style sin of reskinning the entire interface every time there is a version update...
