### ISSUE TITLE
[Discussion] Dropping docked mode

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#117]
It seems like the Transparent Mode added in RC 41 negates any benefit the dock feature was having, since it lets you see the entire screen at a glance and then go back to the old menu. Is there a justifiable reason for keeping the dock that sticks to the footer?

**Comment by aaronliu0130** [comment]
What's "transparent mode"? How do I enable it?

**Comment by aclist** [comment]
Click the "eye with slash" icon on the top right of the KES panel to "see through" the panel at the screen contents. This is useful for when you want to see how an effect is applied without leaving the KES panel. This draws a thin border around the viewport to indicate that you are in a special mode and screen contents cannot actually be interacted with. Once you click anywhere onscreen again, it will return you to KES.

**Comment by aaronliu0130** [comment]
Hmm. I feel like the dock is more useful than transparent mode as you can make changes faster without having to click again to return to the settings.

**Comment by aclist** [comment]
Thank you for your feedback. I will make a poll about it soon.

**Comment by Pamasich** [comment]
I only just discovered it thanks to this thread, but I also agree that docked mode is more useful.

**Comment by aclist** [comment]
Noted.
