### ISSUE TITLE
[BUG] Correct spacing on header icons

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#118]
In desktop view, icons in header are spaced correctly. In a constrained viewport (e.g. mobile, 50%), they bump into each other.

Full view:
![1](https://github.com/aclist/kbin-kes/assets/92275929/31216708-478b-4f90-b130-bd3153e75dc7)

Tiny view:
![2](https://github.com/aclist/kbin-kes/assets/92275929/44a47edc-bbfa-40e7-9bfe-323c9188410b)

**Comment by Oricul** [comment]
Probably need a `min-width` attribute in CSS. Should target 2.0.0.

**Comment by aclist** [comment]
Resolved by 7e84a56c9bebb1eea8edc4a3153d8c83fdf667a1
