### ISSUE TITLE
[BUG] NavBar Subscription Visual Bug - Minor

### ISSUE THREAD

**Issue by McBinary** [aclist/kbin-kes#125]
**Describe the bug**
Incredibly minor visual bug, but it looks like the "My Mags" link highlights the "People" link when selected.

**To Reproduce**
Toggle "Add Subs to NavBar" script > press "My Mags" navbar link.

**Expected behavior**
Highlight "My Mags" nav link

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/139311952/a78ce3e1-08f0-40ee-9bf6-d8882b3ff623)

~[When reporting a bug, you can click the clipboard icon on the bottom right of the KES menu to copy system settings to the clipboard and paste them here]~ This icon is not there...

**KES version:**
- Version number 1.2.0

**Extension and version:**
- Extension: TamperMonkey
- Version number: 4.19.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Browser version: 1.52.130

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by aclist** [comment]
Thanks for the bug report!

> This icon is not there...

Got ahead of ourselves before the next release and updated the template for a feature that is not in the stable version yet. Sorry!

As to the issue, I am investigating and will push a fix later on.

**Comment by aclist** [comment]
This is fixed in 1.2.2. Thank you. Note that when navigating to the People page (if you ever do), it might take a little while for everything to load in, but this seems to be on kbin's side and is not related to anything we are doing.
