### ISSUE TITLE
[BUG] Improved collapsible comments: after 10th reply, nesting breaks

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#130]
- Create a reply chain 9 items deep, then post a 10th reply and thereafter
- The nesting breaks and restarts underneath the old chain. (Intentional?)

**Comment by artillect** [comment]
I've run into this a few times before, but I'm not sure what causes it though since those comments don't appear to be any different from 9th-level and below. I'll take a closer look and see if I can get to the bottom of it

**Comment by aclist** [comment]
Resolved by https://github.com/aclist/kbin-kes/pull/144
