### ISSUE TITLE
[BUG] Mobile navbar occlusion

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#134]
This report comes from a user on /m/enhancement testing the prerelease version

Top-level summary: not enough room for new icons/widgets on mobile view

1. If notification panel is enabled and kbin logo is enabled, not enough room. User proposed alternate, space-saving kbin logotypes: 
  - vanilla kbin folder logo without "kbin" text
  - kibby logo without "kbin text"
2. Disabling the kbin logo with the hide option unintentionally hides the hamburger menu on mobile

@minnieoo do you think you could make cropped SVG versions of the kbin and kibby logos so that we can add them as extra toggle options?

**Comment by minnieoo** [comment]
![kbin_logo_folder_solo](https://github.com/aclist/kbin-kes/assets/137783738/dbfe10ff-d003-4266-a180-25ac3ada2d4b)
![kbin_logo_kibby_solo](https://github.com/aclist/kbin-kes/assets/137783738/ff49b84b-6886-4965-b2ec-b3ea98d2c551)

**Comment by aclist** [comment]
Perfect, thanks so much!

**Comment by aclist** [comment]
Looks great, you can try it in app now

**Comment by minnieoo** [comment]
nice! glad to hear it :D
