### ISSUE TITLE
[BUG] KES doesn't load in Chromium with TM after updating to 2.0.1

### ISSUE THREAD

**Issue by artillect** [aclist/kbin-kes#146]
The KES settings button does not appear, and none of the enabled addons load for me after updating. It looks like the changes to the URLs broke something? Here's the error that appears:

> injected: Refused to connect to "https://raw.githubusercontent.com/aclist/kbin-kes/main/VERSION": Request was redirected to a not whitelisted URL

**Comment by aclist** [comment]
Hotfix is going out in 2.0.2, give it a minute to cache on GitHub's end. I inadvertently dropped that from the `@connect` includes on the supposition that only the initial URL was needed, not the redirect URL.

**Comment by aclist** [comment]
Not the ideal outcome, but luckily I caught it quickly. We should talk more about branch protection rules and mege approvals, but I don't think we have enough contributors to review every merge in a timely fashion. The rubric discussed in the original thread may be too rigid at this point in time.

**Comment by artillect** [comment]
No worries! That's definitely a conversation we should have, and I agree, the original suggestion was probably too strict especially given the limited number of contributors
