### ISSUE TITLE
[MOD] Blacklist posts

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#150]
It might be kinda hard to pull off, but I’ll see what I can do. I’m not sure if KES can be used to (easily) modify the post rankings, but I think randomly hiding them based on a factor you set could work well. So if you set it to 50% for [memes](https://kbin.social/m/memes), it’ll hide half of the posts from there on average.

It’s not perfect, but I think it strikes the right balance between seeing every post and blocking it. I’m busy this weekend but I’ll create an issue on KES’s GitHub repo and someone might beat me to it.

Reposted from kbin:
https://kbin.social/m/kbinMeta/t/193730/Is-there-a-way-to-derank-certain-magazines-on-user#entry-comment-787526

---

Comments: would this just hide the element or use AJAX/pagination to physically load in more content from other pages to replace it? What if your blacklist is so restrictive or there is so much spam from a certain community that it hides most threads on the page? Wouldn't you want to replace that with other content?

**Comment by aclist** [comment]
Perma-hide threads mod is being worked on here: https://github.com/aclist/kbin-kes/tree/patch-hide-posts

Mostly finished, need to make a performance pass.

**Comment by aclist** [comment]
I believe this is finished and working if somebody wants to take a look at it @minnieoo  @artillect 

- Adds a hide button to the footer under threads
- Clicking this adds its ID to GM's permanent private storage; these threads will be hidden in the future
- Disabling this mod restores hidden posts and wipes the permanent storage
- To ensure that hidden posts revert if toggling off while on the current page, a short-term storage of "threads hidden while on this page" is used, avoiding having to check the entire permanent storage for these
- Obviously, works best with infinite scroll so that content continues to fill in as threads are removed

**Comment by minnieoo** [comment]
working well for me C:

**Comment by aclist** [comment]
Great! Take a look at this, I think we finally have the smoking gun as to why KES is "not loading" on mobile iOS: https://kbin.social/m/enhancement/t/219245/KES-running-everywhere-but-iOS

It is loading, the wrench is just buried in the small navbar. Any suggestions on what we can do here?

**Comment by aclist** [comment]
Made  a hotfix that *should* move the wrench into the hamburger menu if the viewport is < 512 px

**Comment by minnieoo** [comment]
this is what happened when i tried it it in ios. safari and using the app "userscripts" for the scripts, it works with ez emoticon. not sure if this is a me issue or what but yea 
![image](https://github.com/aclist/kbin-kes/assets/137783738/98b41138-1094-4c98-be05-c8a8331cd926)
![image](https://github.com/aclist/kbin-kes/assets/137783738/fc95c42f-d5bd-4b64-90b8-54b60214bdd8)
![image](https://github.com/aclist/kbin-kes/assets/137783738/686d1d38-3845-4600-9763-19d73897e652)
![image](https://github.com/aclist/kbin-kes/assets/137783738/bd21e736-a916-4b12-be69-39345ec45c77)
![image](https://github.com/aclist/kbin-kes/assets/137783738/2d2fc6c0-5811-417d-9dc2-a2252309a535)

**Comment by aclist** [comment]
That's not the hamburger menu, it's the subscriptions list :smile_cat: 

Try tapping the hamburger menu at the far left next to the kbin logo

**Comment by minnieoo** [comment]
i opened the wrong hamburger menu in the above screenshots but i don't see it in the other one anyway ![image](https://github.com/aclist/kbin-kes/assets/137783738/ce282bbb-0d97-4c01-b9b6-4eac244e9168)

**Comment by aclist** [comment]
Hmmm :scream:

**Comment by aclist** [comment]
Looks like I put it in the wrong place, the icon should go in this middle panel that opens, then. I think I got it working now, but there might be something else going on here, seems like I can't physically click the hamburger menu if KES is running. I'll update it into teting in a sec

**Comment by aclist** [comment]
So I put it under here:

```
    if (window.innerWidth > 512) {
        kbinContainer = document.querySelector('.kbin-container > menu');
    } else {
        kbinContainer = document.querySelector('.sidebar-options > .section')
    }
```

And it's going where it should now, but I'm not sure if the hamburger menu is going to open correctly. When I return from the rest of the KES code early before setting up the whole modal, I can tap the hamburger menu and the KES icon shows up in there. But if I left it continue through the main loop of building the modal, it seems to block opening the hamburger menu, at least on desktop. Can you try?

**Comment by minnieoo** [comment]
ok ill try

**Comment by aclist** [comment]
Thank you :bow:

**Comment by minnieoo** [comment]
i still don't see the wrench icon and am having no issues opening the menu, it's the same as before essentially :0 

![image](https://github.com/aclist/kbin-kes/assets/137783738/ea4f96c2-d64e-4736-8583-5b20fc52f5e5)
![image](https://github.com/aclist/kbin-kes/assets/137783738/3aa1f652-336b-4d8a-bd44-21d45fda94ab)

**Comment by aclist** [comment]
That's the old version. I bumped the version up, hopefully this causes it to redownload.

**Comment by minnieoo** [comment]
the new version is 2.0.5, no?![image](https://github.com/aclist/kbin-kes/assets/137783738/29cf661e-1a3a-4e0e-997d-b80422722a47)

**Comment by aclist** [comment]
No, I'm committing these into testing right now

**Comment by aclist** [comment]
Should be // @version      2.1.0-beta.14

**Comment by minnieoo** [comment]
oh my bad. the way i make ditzy mistakes every other second omg 🥲

it's working for me now, scripts are working, no issues entering and leaving hamburger menu or KES. works on desktop fine too, no issues.

https://github.com/aclist/kbin-kes/assets/137783738/5c8ba721-d04c-4391-8f11-7cf5cb222212
![image](https://github.com/aclist/kbin-kes/assets/137783738/e8801f1f-cf21-4d40-b268-98d234be00cb)

**Comment by aclist** [comment]
> oh my bad. the way i make ditzy mistakes every other second omg smiling_face_with_tear

Lol, this comment speaks to me

It's fine, I didn't specify, it is my fault

> it's working for me now, scripts are working, no issues entering and leaving hamburger menu or KES. works on desktop fine too, no issues.

Thank heavens! I guess it wasn't blocking continuation of the script, just some anomaly on my end that wasn't triggering the hamburger menu correctly. Still not sure the "why" behind that, but will file it as tech-debt for now.

I'll update this into main and hopefully people's problems are resolved on this front. Thanks so much for testing

**Comment by aclist** [comment]
By the way, we should probably style the icon to be more consistent with the contents of the hamburger menu, yeah?

**Comment by minnieoo** [comment]
> Lol, this comment speaks to me

you have no idea lmfao i am so grateful for your patience, i have embarrassed myself a lot in my learning process with js here but you never have made me felt like a bother or a burden for my mistakes, thank you 🥺💜

>By the way, we should probably style the icon to be more consistent with the contents of the hamburger menu, yeah?

like the way it looks on mobile with the dark bg and dotted border?
![image](https://github.com/aclist/kbin-kes/assets/137783738/de0c104a-2495-4300-a158-b63bdee3f556)

**Comment by aclist** [comment]
> you have no idea lmfao i am so grateful for your patience, i have embarrassed myself a lot in my learning process with js here but you never have made me felt like a bother or a burden for my mistakes, thank you pleading_facepurple_heart

I was actually talking about myself, it's hard to avoid human error when there are lots of moving parts. You are doing awesome, and it's always better to have more than one set of eyes for the sake of sanity checks/workshopping ideas.

> like the way it looks on mobile with the dark bg and dotted border?

Yeah, figured we make a discrete class name here and give give it the same styling more or less, just a wrench inside a box. Not sure if necessary!

**Comment by aclist** [comment]
I'm so grateful to have you as a core member of the KES team, btw! :handshake:

**Comment by minnieoo** [comment]
> I was actually talking about myself

dw i know that! i didnt make it clear, but i didnt assume you were talking about me no worries lolllll. As for the styling, sure it may not be necessary, but for the sake of visual consistency why not :D

**Comment by minnieoo** [comment]
> I'm so grateful to have you as a core member of the KES team, btw! 🤝

thank you so much omg 😭💜💜

**Comment by aclist** [comment]
Do you want to try styling it, btw? I think it might be easier for you since you have a verifiable mobile setup

**Comment by minnieoo** [comment]
sure i will try in a bit

**Comment by aclist** [comment]
Relevant: https://kbin.social/m/enhancement/t/219245/KES-running-everywhere-but-iOS#entry-comment-982615

**Comment by aclist** [comment]
Looks like the other menu items use `var(--kbin-options-link-color)`

**Comment by aclist** [comment]
```
.kes-panel-mobile > #kes-settings-button {
color: var(--kbin-button-secondary-text-hover-color);
background: var(--kbin-button-secondary-bg);
padding: .7rem;
}
```

Here's what I came up with so far, we still need to disable the white border on the bottom and I'll have to insert it as something other than a list item so that it doesn't get that dot next to it

**Comment by minnieoo** [comment]
sorry for my late responses! i've been working on my font resize script. this isn't relevant to the styling above, but in testing my script on ios mobile, i noticed that the wrench icon actually shows up in the correct spot, i forget what version of KES i'm using for testing because i change the number on tamper so it will grab externals faster (even tho tamper is set to update always 😭), but it's older, i thought i should mention it
 ![image](https://github.com/aclist/kbin-kes/assets/137783738/678958ed-1712-4567-8713-02f8c11ae36d)

[script](https://gist.github.com/minnieoo/4575486e5534b05de3e1c6ac419247ae)

**Comment by aclist** [comment]
It depends on the viewport of the phone, what device and what is the screen size? This change is mainly to target people with tall and skinny phones. I don't see anything in the attached script that is different from the old logic we used.

**Comment by minnieoo** [comment]
o okay just thought i'd mention

**Comment by minnieoo** [comment]
oh one sec

**Comment by minnieoo** [comment]
iphone XR 414 x 896 Pixels

**Comment by aclist** [comment]
Try enabling notifications panel, the wrench will probably fall off the screen

**Comment by minnieoo** [comment]
hahah it does, still visible but off to the side yea

**Comment by aclist** [comment]
It'd probably be a good idea to discourage mods from adding icons to the navbar too much, and try to keep this stuff in one place

**Comment by aclist** [comment]
Closing as duplicate of https://github.com/aclist/kbin-kes/pull/173
