### ISSUE TITLE
[MOD] Configurable community "attenuator"

### ISSUE THREAD

**Issue by artillect** [aclist/kbin-kes#152]
**Describe the solution you'd like**
Allow users to reduce the number of posts they see from any number of communities without blocking them entirely. My solution is to randomly hide posts from communities based on a per-community user-configurable factor. Since KES doesn't support adding settings fields on the fly (which would be awesome), they'd be configured as a comma separated list. 

For example `196@lemmy.blahaj.zone 0.4, memes@lemmy.world 0.25` would hide 60% of posts from `196` and 75% of posts from `memes`, just by comparing `Math.random()` to the factor set by the user. One advantage this has over deranking posts (which I don't think would be possible to implement without modifying kbin itself) is that there would be more variety on each refresh of a user's home page. However, you wouldn't be able to eventually see every post from those communities if you keep scrolling, if they are hidden randomly rather than deranked.

**Additional context**
https://kbin.social/m/kbinMeta/t/193730/Is-there-a-way-to-derank-certain-magazines-on-user

**Comment by artillect** [comment]
Ah whoops, just saw that you created that issue, I was in the middle of writing this lol

**Comment by aclist** [comment]
> support adding settings fields on the fly (which would be awesome)

This seems dangerous, when would you use this?

**Comment by artillect** [comment]
I guess it'd be used when you want a user-definable array of options that they can add rows to. RES's account switcher is a good example of what I'm talking about (but it doesn't necessarily need to be as complex):

![image](https://github.com/aclist/kbin-kes/assets/8906201/605a5dbb-b24c-40c9-a6b5-ec6bd15af506)

**Comment by aclist** [comment]
Right. It's not...impossible...just a lot of refactoring for potentially small benefit. I feel like we shouldn't drift too much from the core design logic of: manifest is immutable and defined a priori, mods can do whatever but mustn't mess with KES's menu itself. Maybe if it becomes necessary at some point.

Besides, is having a largeish text area that you can keep adding to demonstrably worse than click, add row, select input, type, move mouse again, click, add row, etc.? Other than prettifying it.
