### ISSUE TITLE
[BUG] Multiple OP tags in comment thread

### ISSUE THREAD

**Issue by McBinary** [aclist/kbin-kes#155]
**Describe the bug**
Multiple people are being identified as the thread OP and tagged throughout the comments. It appears to only happen when the real OP has a comment replying to someone.

**To Reproduce**
Toggle 'Threads >> Add OP Label'

**Expected behavior**
Only a single OP should be tagged in the thread

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/139311952/4821ec05-e007-43a7-b8f9-7449cad99590)

OS: Win32
Agent: Brave 1.52.126
KES version: 2.0.2
Handler: Tampermonkey
Incog: false
Settings: {"lastPage":17,"lastTab":"Debug","addMail":true,"magInstanceEntry":false,"userInstanceEntry":false,"updateTime":false,"toggleLogo":true,"labelOp":true,"initCollapsibleComments":true,"dropdownEntry":true,"notificationsPanel":true,"initKFA":true,"bugReportInit":true}

**Comment by aclist** [comment]
It is resolved by this pull request: https://github.com/aclist/kbin-kes/pull/148

This has been merged into testing and will be released as a hotfix tomorrow.

**Comment by aclist** [comment]
Resolved by e736e3675d319bb6edd03f220ef5b31c43001bb3
