### ISSUE TITLE
[MOD] Remove rounded pfps from Collapsible Comments and add it as a separate mod

### ISSUE THREAD

**Issue by minnieoo** [aclist/kbin-kes#162]
@artillect we noticed your script Collapsible Comments automatically rounds out pfps, and we thought it would be preferable if this was a separate mod for more customization, as not everyone likes rounded pfps and it comes built in to your script.

**Comment by artillect** [comment]
Good call, I initially planned on turning collapsible comments into something like KES and that's a left-over feature from then, I'll remove that and we can roll it into a separate mod

**Comment by aclist** [comment]
Feel free to commit it into https://github.com/aclist/kbin-kes/pull/144 so that it goes in with that patch

**Comment by aclist** [comment]
Resolved by 9af497930741f66e7a326a52d6eb2ae8a061ccf4
