### ISSUE TITLE
[CHORE]  Clean up mobile CSS

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#172]
@artillect @minnieoo  CSS crew

Image submitted by a user:

![Screenshot-20230720-192826-Firefox](https://github.com/aclist/kbin-kes/assets/92275929/cbada5a2-f4d5-4560-b06a-341850bd2de2)

1. On the last kbin theme (purple), install updates button has low contrast and is painful/hard to read. Are we using kbin's color theming correctly for this button?
2. More spacing between header icons to make tapping easier
3. Reset button is huge and occludes footer
4. Bug icon is getting thrown out of alignment
5. Install button is out of alignment

3 and 4 are both related to the grid padding

**Comment by minnieoo** [comment]
taking a look

**Comment by minnieoo** [comment]
> Are we using kbin's color theming correctly for this button?

it is indeed the correct link color for this theme, but it's obviously not gonna work on that green so yea, ill try and fix it
![image](https://github.com/aclist/kbin-kes/assets/137783738/67c613a6-36bf-48c7-b18e-98b3cb0699d9)

**Comment by aclist** [comment]
Take a look at some of the bg vars, `var(--kbin-alert-danger-bg)` seems pretty consistent on all themes, but maybe not the most handsome? The success-bg currently being used seems like it is not designed for this use case, should be used sparingly.

**Comment by aclist** [comment]
Another thing I noticed is that the "updates available" notifier is all but invisible on the purple theme:

![a](https://github.com/aclist/kbin-kes/assets/92275929/3f7e65ad-ad8d-4394-90ad-d82f7568bf91)

**Comment by minnieoo** [comment]
`var(--kbin-alert-danger-bg)` aint gonna work unfortunately, on some it does, some it doesn't. have a feeling color blind people especially will struggle here with this one. ill see about other options. also, noted about the update notifier
![image](https://github.com/aclist/kbin-kes/assets/137783738/983b510f-a96b-41f8-a86c-c432ef17e6e9)

**Comment by aclist** [comment]
The original user who reported it is colorblind

Guess we need higher separation between fg and bg text?

**Comment by minnieoo** [comment]
yea definitely, i'm looking for css vars that have the most contrast between each other in all themes

**Comment by minnieoo** [comment]
i would want to say the upvote vars, as that *should* be well contrasted on all themes, but some themes actually have the same contrast issue :smiling_face_with_tear: :smiling_face_with_tear: 

![image](https://github.com/aclist/kbin-kes/assets/137783738/9cf17b7c-923c-4eeb-90f6-87ed54e10749)

using: `var(--kbin-vote-bg)` for bg and `var(--kbin-vote-text-color)` for color, and we could experiment with a hover color from there if its necessary (though i think it's pretty clear what it does with or without hover color)

![image](https://github.com/aclist/kbin-kes/assets/137783738/f3034c71-3cd1-483e-a5c8-dc57954e9a12)

though maybe to combat this we can just add a border with the  `var(--kbin-vote-text-color)`? (first is 2px, 2nd is 1px)

![image](https://github.com/aclist/kbin-kes/assets/137783738/21ee17d9-8452-46c3-8396-aa87f395c699)
![image](https://github.com/aclist/kbin-kes/assets/137783738/dcdc1e48-62bc-4fa2-88d4-face54c98948)

**Comment by aclist** [comment]
Right, I think some of the themes themselves are half-baked right now and their colors are not set up exactly right. 

We don't need a hover color per se, we can just use opacity like we are now.

The border idea seems decent provided it works on all themes. I am pretty meh about box shadows in general, and the design of the interface right now is pretty flat, so seems out of place.

**Comment by minnieoo** [comment]
agreed on box shadows, not really a fan lol, but thought i'd present the option anyway. ill test on the rest of the themes now and update you

**Comment by minnieoo** [comment]
whyyyyy light theme's contrast sucks 🥲 🥲 so close
![image](https://github.com/aclist/kbin-kes/assets/137783738/6ef21d27-c171-4607-86b3-ba5cdf65fbdc)

**Comment by aclist** [comment]
I was actually thinking you'd do idea 1 but add a border to all of them, does that help at all?

**Comment by minnieoo** [comment]
with `var(--kbin-alert-danger-bg)`?

**Comment by aclist** [comment]
No, in the post after that you had three ideas (I thought), but they looked pretty similar to one another so now I guess it was actually two ideas with similar looking screenshots. But in the first pic you had a green button on the gray theme, so maybe that was unintentional?

The fact of the matter is that the light theme is terrible lol.

**Comment by aclist** [comment]
I am mocking it in Stylus now to see your edits

**Comment by minnieoo** [comment]
oh, that was actually due to the colors for solarized dark on the panel not loading in 🥲 , sometimes the panel stays grey despite the theme, but it corrects itself upon opening and closing

**Comment by aclist** [comment]
Try this,

```
.kes-version .new {
	background-color: var(--kbin-vote-bg) !important;
	border: 2px solid var(--kbin-vote-text-color);
}
.kes-version .new:hover {
	opacity: 0.4
}
```

Don't set the fg text color and let it set its own. Light theme defaults to a bluish color. I think this is readable on all themes, albeit spartan.

**Comment by aclist** [comment]
Second edit (reverse opacity):

```
.kes-version .new {
	background-color: var(--kbin-vote-bg) !important;
	border: 2px solid var(--kbin-vote-text-color);
	opacity: 0.4
}
.kes-version .new:hover {
	opacity: 0.8
}
```

**Comment by minnieoo** [comment]
o yea that's a good solution, light theme is legible finally :0

**Comment by aclist** [comment]
Item 1 resolved by 12650d8d812f7dadf79cc72943e8683c500f55f3

How about the updates icon? Should be a lot easier, I think

**Comment by minnieoo** [comment]
yea it should be, ill see about it rn

**Comment by minnieoo** [comment]
this is with `var(--kbin-upvoted-color)`, once again light theme (dark blue bg) is the odd man out. pretty much everything is diluted with that one.
![image](https://github.com/aclist/kbin-kes/assets/137783738/b6e057d6-faeb-4935-b61f-9ec8f0cd7ba2)
![image](https://github.com/aclist/kbin-kes/assets/137783738/7af69236-736e-4baa-97a0-6c858d54b44b)
![image](https://github.com/aclist/kbin-kes/assets/137783738/5595e020-aa6e-47ab-b3de-dd3f55fbf133)
![image](https://github.com/aclist/kbin-kes/assets/137783738/3ff8ca4e-0690-437c-8fc1-4067fb88ea8f)
![image](https://github.com/aclist/kbin-kes/assets/137783738/bde68707-cce9-488a-88d0-64c6141c8fc9)
![image](https://github.com/aclist/kbin-kes/assets/137783738/9df3ca5a-9a43-4742-8091-24ce8496a894)

and this is `var(--kbin-danger-color)`. i can understand why red may not be preferable, but it certainly does bring attention to it, except in light theme bc its still fuckin diluted lol
![image](https://github.com/aclist/kbin-kes/assets/137783738/1932dc3f-6ee5-4755-a8d8-ac402f38c005)
![image](https://github.com/aclist/kbin-kes/assets/137783738/d3bcb5fb-f7d2-443d-ad31-715b0c55668e)
![image](https://github.com/aclist/kbin-kes/assets/137783738/c19c0585-e8c9-4285-99ab-2cf6365f622a)
![image](https://github.com/aclist/kbin-kes/assets/137783738/6608fa69-fa55-4abe-aff0-a001e611c1da)
![image](https://github.com/aclist/kbin-kes/assets/137783738/71be89de-33e4-4a1b-84fe-526ccb451294)
![image](https://github.com/aclist/kbin-kes/assets/137783738/4810cd12-d662-480d-a060-5b7d7915adeb)

**Comment by aclist** [comment]
Best guess is the white theme is supposed to be a high visibility/accessibility theme, so colors look like photonegatives at times. Nix on the red. There aren't a lot of choices here, the green is probably good enough. The default purple bg theme is just blah.

**Comment by aclist** [comment]
Could also just inherit the same color as the icon, not sure if that is good or not.

**Comment by minnieoo** [comment]
i don't think people would necessarily miss it if it was the same color as the icon, but it wouldn't call attention to itself. i agree that the green is good enough, anyone using light theme anyway, considering how bad the contrast is, ought to be able to spot it, they must have good vision and aren't needing enhanced visual accessibility. i think it stands out well enough.

**Comment by aclist** [comment]
Seems like a best-effort approach here is good enough, can we drop the hover color on the notifier then?

People using light theme: https://www.youtube.com/watch?v=PWFF7ecArBk

**Comment by minnieoo** [comment]
> People using light theme: https://www.youtube.com/watch?v=PWFF7ecArBk

lmfao that's so real, i don't know how they do it 💀, cant believe its still the default on a lot of sites

> can we drop the hover color on the notifier then?

if you'd like, what do you think?

**Comment by aclist** [comment]
Feels like managing one color is less problematic than two, and seems like they really only give you dull orange, green, red, and white, so feels like if green is the base notifier color, none of those really works? Keep it simple

**Comment by aclist** [comment]
As far as I can tell, `kbin-success-color` is identical to `kbin-upvoted-color`, and seems more semantically correct, so going with that one

**Comment by minnieoo** [comment]
sorry for my late response, i fell asleep. yea they are pretty much the same, i just chose whichever green i had spotted first at the time

**Comment by aclist** [comment]
No problem. I'm not sure about issues 3 and 4, maybe arti will have an idea about it

**Comment by aclist** [comment]
For now, I think I've managed to force these elements into alignment when the device is smaller than 576px, but it's a bit of a hack atm since I hardcoded the pixel offsets to look reasonably correct. The main problem is that the version number/update button in the header doesn't fit well on mobile, so it'd probably be better if we checked the `innerWidth` when setting up the menu itself, and insert that element into its own div if on mobile, then use grid order to put it after the header but before the sidebar.
