### ISSUE TITLE
[FEAT] Accessibility category

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#177]
Add a sidebar tab for this. Font resizing mod should go in there

Also relevant: https://kbin.social/m/kbinMeta/t/229830/User-Script-kbin-social-make-upvote-blue-down-is-red-for-colorblind

**Comment by minnieoo** [comment]
this would be nice :D

**Comment by minnieoo** [comment]
speaking of the upvote and downvote colors, i think it makes sense to add a script for the accessibility category where the user can simply choose which colors they'd like for the upvote/downvote colors, or perhaps even a couple more relevant things in addition to that to be compact, something like this:

![image](https://github.com/aclist/kbin-kes/assets/137783738/a7bbc415-66f4-47bd-975e-e7d663910637)

**Comment by aclist** [comment]
Yep, I agree, true accessibility == you can set whatever you want, not what we think is good for you

**Comment by aclist** [comment]
Category added in 183b4fcea81dc3eb1bf700f1c7a1d35b17b9ee55
