### ISSUE TITLE
[MOD] Port Subscriptions Panel to KES

### ISSUE THREAD

**Issue by sterno900** [aclist/kbin-kes#186]
Request to port  Subscriptions Panel to KES :
https://greasyfork.org/en/scripts/469139-kbin-subscriptions-panel

<img width="961" alt="Screenshot 2023-07-24 204556" src="https://github.com/aclist/kbin-kes/assets/50577964/670e0e5e-d53a-43fd-9ac3-8e38d193f56f">

**Comment by aclist** [comment]
Thanks for the report. This is something we will look into after the upcoming 2.1.0 release. It is quite a large script which has its own rules for storing and managing settings, so would have to adapt several things to make it compliant, but it is not impossible and has been asked for several times.
