### ISSUE TITLE
[BUG] Notification Panel - Not clickable

### ISSUE THREAD

**Issue by Rhaedas** [aclist/kbin-kes#197]
The Notification Panel extension worked as designed with 2.1.1 (I think). I had noticed it not working with the 2.1.0 update, but before I could report it 2.1.1 was released and I don't remember any issues. After 2.1.2 was put out, at first I thought it had broken again, as I could see the bell and numbers of messages, but couldn't click on it. However, I found out I could click on the bell once I cleared the messages. After getting another notification number pop up, I figured out the issue. I can still click on the small part of the bell seen from under the number, but not the number itself as I originally could before.

**To Reproduce**
Have the Notification Panel active.
Click on the bell to see past messages.
When an unread message is present, try to click on the number part of the icon.

**Expected behavior**
Clicking anywhere should open up the panel, not only the sliver of bell showing.

**KES version:**
- Version number [2.1.2]

- Extension: ViolentMonkey

 - OS: Windows 10
 - Browser Firefox

**Comment by aclist** [comment]
Thanks for reporting it. Sure, that's an easy fix. I believe there were some changes to kbin itself between 24-36 hours ago that were causing the panel to not open at all, which is why you might have seen some erratic behavior.

I did confirm the counter/bell click action you talked about and will fix it. There's also the question of whether the inbox notification counter (for messages) should be hidden and combined into the notifications panel counter.

**Comment by aclist** [comment]
This should be fixed in 2.1.3, please confirm. I also added some other fixes:

- Merge unread message/unread notification count into one number
- Properly clean up navbar when toggling off extension, restoring unread count badges

**Comment by Rhaedas** [comment]
Working as expected now, thanks. The color change for the numbers is new too, I think? Definitely jumps out better.

**Comment by aclist** [comment]
Thank you. kbin has two badge colors, a default BG and a "danger" BG. It uses the "danger" BG for message notifications and the default one for thread reply notifications. I decided to just merge them into a single counter and use the danger BG.
