### ISSUE TITLE
[MOD] Disable NSFW Blur

### ISSUE THREAD

**Issue by jobobby04** [aclist/kbin-kes#198]
**Is your feature request related to a problem? Please describe.**
Its annoying to have to hover on NSFW posts to view the images

**Describe the solution you'd like**
I think an option to disable the NSFW blur that happens on NSFW Images would be useful for those who don't want the blur.

**Describe alternatives you've considered**
I've looked in the KBin settings and found no alternatives for disabling it.

**Additional context**
I've looked at the HTML, it seems like hovering fires a javascript block that disables or enables the blur with CSS.

**Comment by aclist** [comment]
Thanks for the suggestion. Can you list an example of where to find these posts?

**Comment by jobobby04** [comment]
[Warning NSFW](https://kbin.social/m/boobs@lemmynsfw.com)

**Comment by aclist** [comment]
Alright, it is an easy fix, will be included in the next release.

**Comment by jobobby04** [comment]
Awesome, thanks.

**Comment by aclist** [comment]
Resolved by e0e5d7a in testing, enters stable branch as of 2.2.0, ca. next week

**Comment by aclist** [comment]
This feature is now live and can be found under the `Threads` page of the sidebar.
