### ISSUE TITLE
[CHORE] Preview images

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#203]
@minnieoo 

yea sure i can do that. do we want them in `/images` or perhaps a separate folder like `/screenshots` or `/previews`? there might be quite a few of them, not sure if it matters if they are mixed up with the current example images and the kibby images but thought i'd ask anyway. also what is the field called? links? would i be doing something like `"link": "/images/mod-preview.png"` on the mods i take the sc's for?

_Originally posted by @minnieoo in https://github.com/aclist/kbin-kes/issues/194#issuecomment-1657036710_

**Comment by minnieoo** [comment]
should /previews be within /images?

**Comment by aclist** [comment]
Yeah, definitely. `/images/previews/XXX`

**Comment by aclist** [comment]
Duplicate of 204
