### ISSUE TITLE
[BUG] Backgrounds on multiple pages aren't being displayed

### ISSUE THREAD

**Issue by spaceghost24** [aclist/kbin-kes#231]
**Describe the bug**
Certain divs (which as far as I've found are all children of main, with both the section class and the content id) are being given the display:unset style by the script, even with all of the features disabled. This 1) removes the background and 2) conflicts with the styling for .section to somehow create two bars along the left side of the element. Examples are on the "add new thread" page (https://kbin.social/new/article), the login page (https://kbin.social/login while logged out), and in almost every tab of the "magazine panel" moderation tool.

**To Reproduce**
1. Go to https://kbin.social/new/article with the script enabled. Alternatively, with the script still off, add the display:unset style manually to the #content div on that page via the inspector.
3. The box beneath the new thread form should be mostly transparent except for two bars to the left and slightly above and below it, overlapping with other objects on the page.

**Expected behavior**
The divs should have solid gray backgrounds across their entire width, rather than bars on their left side.

**Screenshots**
The "new thread" page:
![image](https://github.com/aclist/kbin-kes/assets/84802703/647d503c-d523-4c23-8184-cf6276a2c2a6)
The actual elements and styles of the #content div on the new thread page:
![image](https://github.com/aclist/kbin-kes/assets/84802703/c959743c-87df-4627-8f2e-a64ca98557fc)
The moderators tab of the magazine panel:
![image](https://github.com/aclist/kbin-kes/assets/84802703/46d90129-1d73-4642-920e-9b35c60ff5bc)

**KES version:**
- Version number 3.1.0

**Extension and version:**
- Extension: TamperMonkey
- Version number: 4.19.0

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 Cinnamon (And previously Ubuntu 20.04 on a different device, same issue but probably earlier versions of the browser/extension/script)
 - Browser: Firefox
 - Browser version 120.0.1

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 14
 - Browser: Firefox
 - Version: 120.1.0

**Additional context**
I spent awhile playing around with the css before I originally reported this issue to make sure I understood where it was coming from. I'm fairly confident that the display:unset style is the only thing wrong here: toggling it off and on again fixes and unfixes the issue, and I can induce it from scratch with the script disabled just by adding that one style manually without needing to change anything else.

**Comment by aclist** [comment]
Thank you for the detailed report. I have identified the offending issue as stemming from the way a mod was disabling itself. This will be fixed in a forthcoming update.

**Comment by aclist** [comment]
Resolved in 3.2.0
