### ISSUE TITLE
[CHORE] Encapsulate mods and call by object

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#255]
The purpose of this change is to bundle atomic mods into a single JS file and source that file in the KES headers, rather than making 40+ requests. As a side effect, it simplifies the function entry logic and cleans up the auto masthead.

To be changed
---
- [x] Refactor all mods in mod directory such that they are encapsulated with an outer function. All internal functions must be private
- [x] Refactor KES generation script to concatenate mod contents into an object with qualified key names
    - Mod dirname, file basename, and key name must be identical (key name is inherited from basename)
    - Check for namespace collisions when approving PRs (could be automated)
 - [x] Refactor function entry logic to interpolate stringwise mod names from manifest:
```
let mod = json[i].entrypoint
funcObj[mod](bool)
```
To be removed
---
- [x]  ESLint global exports from KES masthead
- [x] Legacy funcObj from KES masthead

To be added
---
- [x] Add concatenated functions file to `@requires` headers
- [x] Automatically update JSON in place with qualified entrypoint name

TODO
---
- [x] Add function concatenation script to build routine

Note: Issue an advisory to use the KES export tool after a release bump so that backups are not stale

**Comment by aclist** [comment]
This issue has implications for #253 (and as a side effect, ameliorates the headroom issue from #252), https://github.com/Pamasich/kbin-kes/issues/63, and https://github.com/Pamasich/kbin-kes/issues/64

**Comment by Pamasich** [comment]
I do have one more question in regards to refactoring the mods. I currently have a documentation comment on the entrypoint function or class (if I used one) of my mods.

Like this example from the one I just submitted:

```
/**
 * This mod aims to fix a current kbin issue.
 * On some views, like All Content, the pagination is broken. The arrows behave like they're on
 * the first page, regardless of which they're actually on. This mod is meant to fix the issue
 * by manually rewriting the arrows to work correctly.
 * 
 * @param {Boolean} isActive Whether the mod has been turned on
 */
function fixPaginationArrows (isActive) {
```

Do I need to move those inside the function if I want to keep them? Or does it not matter?

**Comment by aclist** [comment]
I was just testing it slightly, and don't think it would have any adverse implications, since anything commented out is just going to get added in verbatim into the concatenated file and ignored:

```
const funcObj = {
    hide-reputation: 

    // ==UserScript==
    // @name         kbin Vote Hider
    // @namespace    https://github.com/aclist
    // @version      0.2
    // @description  Hide upvotes, downvotes, and karma
    // @author       artillect
    // @match        https://kbin.social/*
    // @license      MIT
    // ==/UserScript==
    
    function hideReputation (toggle) {
        if (toggle) {
            $('#sidebar > section.section.user-info > ul > li:nth-child(2)').hide();
            document.styleSheets[0].addRule('.user-popover ul li:nth-of-type(2)','display:none')
        } else {
            $('#sidebar > section.section.user-info > ul > li:nth-child(2)').show();
            document.styleSheets[0].addRule('.user-popover ul li:nth-of-type(2)','display:initial')
        }
    }

    hide-sidebar: 

    function hideSidebar (toggle) {
    
        const obj = {
            sidebar: '#sidebar',
            mags: '#sidebar > .related-magazines',
            users: '#sidebar > .active-users',
            posts: '#sidebar > .posts',
            threads: '#sidebar > .entries',
            instance: '#sidebar > .kbin-promo',
            intro: '.sidebar-options > .intro'
        }
    
        const settings = getModSettings('hide-sidebar');
    
        const keys = Object.keys(obj);
    
        if (toggle) {
            for (let i = 0; i< keys.length; i++) {
                let key = keys[i]
                if (settings[key]) {
                    $(obj[key]).hide();
                } else {
                    $(obj[key]).show();
                }
            }
        } else {
            for (let i = 0; i< keys.length; i++) {
                let key = keys[i]
                $(obj[key]).show();
            }
        }
    }
 }
 ```
 
 As for whether this pollutes the file, I don't think so. Concatenation should be agnostic about the contents of those mods and doesn't need to scrub comments or other markup.

**Comment by aclist** [comment]
After flattening all of the mod directories to underscores (hyphens weren't working in identifiers in the object-of-functions), it seems to be working on the branch https://github.com/aclist/kbin-kes/tree/patch/func-obj. I also updated the manifest and func.js generators accordingly. I did have to make one change to the alt-content-access mod in order for it to comply: https://github.com/aclist/kbin-kes/commit/5735831468117ea5130e9b1d581f1920ca024941. I know this looks a bit weird, but it works.

**Comment by aclist** [comment]
I noticed that this change seems to ignore mod settings in localStorage when using the testing branch version on kbin.social, with everything reverted to the default state of OFF. Was it always the case that mod settings are local to a particular branch version? When I use the stable version of KES on the main branch, it loads local mod settings correctly. Or did this patch inadvertently change something about how localStorage namespaces are used by mods?

**Comment by Pamasich** [comment]
> Was it always the case that mod settings are local to a particular branch version?

No. I have KES installed twice (once the stable version and once my own testing version from my tests branch). I turned on my alt-all-content-access mod and set the button hide setting to off, then switched which KES I use and it was still off. I then turned it on and switched back to the one I was originally using. It was on there too.

So this seems to be a new issue.

**Comment by aclist** [comment]
Ah, it's because I renamed the entrypoint keys to match the directory names, whereas the old localStorage uses the original entrypoints defined in the manifest. Will have to think about whether to go back to the legacy names or whether there should be a migration function to update the localStorage.

**Comment by aclist** [comment]
This should be fixed in https://github.com/aclist/kbin-kes/commit/cd558f7b5cad8990cd0bd491bf2b0fd4ae67f8b9; I made a mapping from legacy localStorage names to the new versions, and this will perform a check before initializing the mods. If an old settings stub is found, it gets removed and updated with the new key name, and if it was previously set to on, that setting is inherited. 

This should ensure that migrating from the old to new names is transparent to the user and happens one time, after which time they are on the new names.

Eventually, we can drop this logic, but this would break people carrying over very old backup files and trying to restore them at some later date, unaware of this change. Will probably have to issue an advisory after release warning users to backup their settings file again to reflect the new structure.

**Comment by aclist** [comment]
Closing as resolved
