### ISSUE TITLE
[CHORE] Mbin compatibility testing

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#260]
Working
---
  - [x] Add a notifications panel
 - [x] Add subs to navbar
 - [x] Adjust colors
 - [x] Alpha sort subs/followers list
 - [x] Always expand post bodies
 - [x] Dropdown links
 - [x] Expand post text in thread index
 - [x] Hide reduces
 - [x] Hide reputation
 - [x] Hide favorites
 - [x] Hide sidebar elements
 - [x] Hide thumbnails
 - [x] Easy emoticons
 - [x] Add OP label
 - [x] Magazine instance names
  - [x] Navbar icons as text
 - [x] Rearrange post order
 - [x] Show thread/microblog delta since last visit
 - [x] Permanently hide posts
 - [x] Collapsible comments
 - [x] Subscriptions omnibar
 - [x] Mobile view cleanup
 - [x] Repair Lemmy code blocks
 - [x] Toggle logo
 - [x] User instance names

Fixed (used for changelog)
---
 - [x] Softblock magazines: mod was removing the wrong parent element on mbin
 - [x] Federation Awareness: added support for mbin with a more generic hostname check
 - [x] Alternative access to All Content
 - [x] `--kbin-footer-bg` is not a supported var on mbin, resulting in KES modal dialogs (search dialog, etc.) appearing transparent
- [x] Show recipient on compose: the mod does not label recipient when composing a new message, only when replying from inbox
- [x] Hover indicator: initial values not being applied if mod was not previously used
- [x] Add mail icon: fixed an issue where it was possible to send mail to yourself
- [x] Verbose timestamps: since this is a hardcoded exclusion, updated to support new entrypoint name format
- [x] Move federation warning to sidebar: updated to support profile pages, since they use the same element
- [x] Report bug button on posts: reworded description for clarity about this applying only on comments, not threads
- [x] Unblur NSFW thumbnails: support magazine logos, circular avatars, and hide sensitive content filters on mbin
- [x] Checkmark on subbed mags: fixed an issue where unsetting verbose magazine instance names would remove checkmarks due to conflicting elements

WIP
---
- [x] Code Syntax Highlighting: add repair codeblocks dependency
- [x] Change font size: refactor to interpolate computed font size and toggle off dynamically

**Comment by Pamasich** [comment]
I haven't had time to test mine yet, but

- fix_codeblocks, if it's even needed on mbin, should have no issues at all; it just looks for `pre code` blocks which I doubt mbin changed.
- alt_all_content_access currently doesn't check if the All Content button exists before changing the title link. So it doesn't account for mbin not having that view, and will change the title regardless, which should cause it to link to a non-existing page. I'll add a check for that in a moment, so the mod only executes if the All Content button is present.

**Comment by Pamasich** [comment]
`Repair Lemmy Code Blocks` isn't needed on mbin, but doesn't cause issues either. I've added a note that it's useless on mbin in #263.

**Comment by Pamasich** [comment]
> - Add a notifications panel
>    - Panel itself works, did not test message interactions (need to add messages to inbox to test)

I just tested it, can receive notifications and go to them by clicking. Seems to work at a glance, though I didn't look deeper than that.

**Comment by Pamasich** [comment]
I turned on `Federation Awareness` on kbin.run (an mbin instance). Every user seems to use the `federated` color, even kbin.run users, which should be using the home instance color.

For example [here](https://kbin.run/m/SciFi).

**Comment by aclist** [comment]
[

> I turned on `Federation Awareness` on kbin.run (an mbin instance). Every user seems to use the `federated` color, even kbin.run users, which should be using the home instance color.
> 
> For example [here](https://kbin.run/m/SciFi).

The mod looks for the string `copy original url` as a match condition, but on mbin it is `Copy original URL`. https://github.com/aclist/kbin-kes/blob/deb93c6a913e1876c179801438852e703422772c/mods/kbin-federation-awareness/kbin-federation-awareness.user.js#L138

**Comment by aclist** [comment]
> > I turned on `Federation Awareness` on kbin.run (an mbin instance). Every user seems to use the `federated` color, even kbin.run users, which should be using the home instance color.
> > For example [here](https://kbin.run/m/SciFi).
> 
> The mod looks for the string `copy original url` as a match condition, but on mbin it is `Copy original URL`.
> 
> https://github.com/aclist/kbin-kes/blob/deb93c6a913e1876c179801438852e703422772c/mods/kbin-federation-awareness/kbin-federation-awareness.user.js#L138

Fixed per db5c82b

**Comment by Pamasich** [comment]
The hover indicator doesn't work for me on kbin either. I think it's just broken in general.

**Comment by Pamasich** [comment]
The syntax highlighting mod works for me btw on mbin.

**Comment by Pamasich** [comment]
> The mod looks for the string `copy original url` as a match condition, but on mbin it is `Copy original URL`.

I think this should go into "other non-mbin issues found" then.

Like, this means the mod won't work if a different language than English is used (just tested that theory with German). I think at the very least this should be mentioned in the description, if it can't be fixed.

**Comment by aclist** [comment]
> The hover indicator doesn't work for me on kbin either. I think it's just broken in general.

Hmm, it works for me on kbin without further modifications.

> Like, this means the mod won't work if a different language than English is used (just tested that theory with German). I think at the very least this should be mentioned in the description, if it can't be fixed.

That's a good point! I think the intent behind this decision is that using the ordinal index of items in the list is not reliable because there could be any number of items in the dropdown at some point in time. (Or, indeed, if some mod added more to a dropdown.) But parsing for this string seems brittle as well. If only there were a better place to grab the original URL...

**Comment by aclist** [comment]
Unless I'm misunderstanding the purpose of the mod, it looks for the URL of the **originating instance** where the post was made, and does so by checking the contents of the dropdown to get the "original URL". But isn't it the case that the for the **poster** of the original URL on the originating instance (`user@instance`), the user's instance has to be the same as the originating instance?

Or is there some rare scenario (crossposting?) where the OP can post from one instance to another instance? Is this even possible? Wouldn't the originating post always come from a user on the selfsame instance?

If so, can't we just parse the username in the thread index and use this as the qualified domain name?

**Comment by aclist** [comment]
```diff
1,11c1,8
<     function findHostname (links) {
<         let host
<         let str
<         const instance = getInstanceType();
<         switch (instance) {
<         case "kbin":
<             str = "copy original url"
<             break;
<         case "mbin":
<             str = "Copy original URL"
<             break;
---
>     function findHostname (op) {
>         let arr
>         if op.includes('@') {
>             //other instances
>             arr = op.split('@')
>         } else {
>             //home instance
>             arr = op.split('/')
13,20c10,11
<         links.forEach((link) => {
<             const innerString = link.innerHTML.trim();
<             if (innerString === str) {
<                 host = new URL(link.href).hostname;
<             }
<         });
<         return host
<     }
---
>         return arr[arr.length - 1]
>     };
30,31c21,22
<             const copyLinks = article.querySelectorAll('footer menu .dropdown a[data-action="clipboard#copy"]');
<             const hostname = findHostname(copyLinks);
---
>             const op = article.querySelectorAll('.user-inline')
>             const hostname = findHostname(op);
```

**Comment by Pamasich** [comment]
> > The hover indicator doesn't work for me on kbin either. I think it's just broken in general.
> 
> Hmm, it works for me on kbin without further modifications.

Oh, now it works. Not sure why though. I changed the outline settings, the color and thickness, and that seems to have fixed it. But even after resetting them and reloading the page it now works.

**Comment by Pamasich** [comment]
Yeah, same on mbin. I just opened kbin.run (which I modified my test KES to support), turned it on, and as expected it didn't work. Then I opened the color picker, pushed the slider, and noticed the outline appear. It now works flawlessly on this mbin instance.

**Comment by aclist** [comment]
Hmm, noted. The mod is probably checking for some config parameters at runtime and they aren't initialized to anything. The manifest shows that those fields have initial values set, but maybe they aren't being applied correctly.

**Comment by Pamasich** [comment]
Yeah, it's the color specifically. Maybe the default value of color pickers doesn't work correctly?

**Comment by aclist** [comment]
Hover indicator issue was fixed in 1b9d144

**Comment by aclist** [comment]
@Pamasich Everything should be working now, and I am preparing the 3.4.0 release. Now would be a good time to do any final sanity tests and check the CHANGELOG.md to see if anything was omitted.

I've also created an additional build tool that runs the function concatenation script and then uploads a copy as a Gist to the user's GitHub page, then updates the requires URL in KES and copies the contents to the clipboard. This should allow for prototyping local changes via a single-line invocation, since you can then paste the entire contents into *monkey. I haven't fully documented its usage yet, though.

**Comment by aclist** [comment]
Found another issue with the syntax highlighting mod where the collapsible headers are not responding, and have not identified the root cause yet.

**Comment by Pamasich** [comment]
> Found another issue with the syntax highlighting mod where the collapsible headers are not responding, and have not identified the root cause yet.

It seems to only not work on page load. If I turn the mod off and then on again, it works as expected.

**Comment by Pamasich** [comment]
So I tested the syntax highlighting headers on mbin (kbin.run) with nothing except syntax highlighting and repair codeblocks turned on, and it worked without issue. So it's either the instance/software (kbin.social vs kbin.run) or another mod that's causing the issue.

**Comment by Pamasich** [comment]
Actually, now it works for me on kbin.social too, weird. Can't help troubleshooting this then if I can't reproduce it anymore.

**Comment by aclist** [comment]
> It seems to only not work on page load. If I turn the mod off and then on again, it works as expected.

I observed this as well. Works statically once the DOM has loaded, but not on initial page (re)load. Does not seem to be affected by the absence or presence of a dependency. It seems like the event listeners never get attached, but not sure why yet. If this becomes unnecessarily complicated, I may drop the fancy header features until further notice in favor of a static label. 

I'll try what you said and see if another mod is conflicting.

**Comment by aclist** [comment]
Your comments put me on the right path: it's definitively caused by some collision with the collapsible comments mod.

**Comment by aclist** [comment]
Thank you. I've thought about this a lot, and it seems to underscore the possible pitfalls of interactions between really complex mods. On the one hand, it goes back to the conversation about load order, but it's not quite so easy as just putting code highlighting at the end of the JSON manifest and letting it load last, per se.

The issue is that the collapsible comments mod could still be turned on and off at will after that, so the problem will continue to surface. This mod is one of the more destructive mods in that it takes all of the comments, creates new elements for them, and reinserts them up and down the tree to create a nested effect. This completely obliterates any nested listeners on the original elements.

I think the fix here is to use event delegation and have the code highlighting mod assign its listener to something higher up in the tree that will be immune to modifications: in this case, the `#comments` element. Collapsible comments does all of its work on elements under that. 

Rather than adding listeners to every code block icon, a single listener covers the entirety of the comments section, and the event is filtered to only apply when the target === the actual icon being clicked.

This should resolve the issue in the least invasive way possible.

**Comment by aclist** [comment]
OK, after much hand-wringing, it should be fixed, and these mods play nicely with each other now.

**Comment by Pamasich** [comment]
> Now would be a good time to do any final sanity tests and check the CHANGELOG.md to see if anything was omitted.

I think the changelog should mention that the syntax highlighting mod now requires the repair codeblocks mod to be turned on / gets turned off when the latter is turned off. I forgot if you added dependencies for any other mods too, but same applies to them.

**Comment by aclist** [comment]
At first, I started adding dependencies between the omnibar and thread checkmarks, but I decided to wait until the fetch subscriptions logic is abstracted, since it doesn't make much sense to have these actively depend on each other. I'll update the changelog.

**Comment by Pamasich** [comment]
@aclist I just noticed another incompatibility.

With `Collapsible Comments` turned on, it seems like the vote buttons are getting displaced for me on mbin. Might have to do with recent changes to the mod, or maybe mbin. I've seen the issue on kbin.run and fedia.io.

They seem to be moved to the end of comment chains and way pushed to the right. 

[Here's an example image of the issue.](https://i.imgur.com/FA0vwGh.png) I've made sure my custom CSS isn't the cause, nor does mbin behave weird without the mod..

**Comment by Pamasich** [comment]
Also I'm noticing the double OP label there.

**Comment by aclist** [comment]
> @aclist I just noticed another incompatibility.
> 
> With `Collapsible Comments` turned on, it seems like the vote buttons are getting displaced for me on mbin. Might have to do with recent changes to the mod, or maybe mbin. I've seen the issue on kbin.run and fedia.io.
> 
> They seem to be moved to the end of comment chains and way pushed to the right.
> 
> Here's an example image of the issue: ![](https://camo.githubusercontent.com/73410403d768d04950b1260717ae06448cdd62968ff1f69e1f985c03e303bc6f/68747470733a2f2f692e696d6775722e636f6d2f464130767747682e706e67) I've made sure my custom CSS isn't the cause, nor does mbin behave weird without the mod.

Thankfully, it looks like an easy fix. The mod CSS defines a grid template area and refers to the vote section by the classname `vote`, but it should be `.aside` on mbin, and this fixes it instantly. I can't cross-check this on kbin.social at the moment, because it's down, but looks either the new CSS can be used for both, or we load alternate stylesheets depending on the instance type.

As for the OP label, seems mbin adds its own OP label, so this mod should be disabled on there.

**Comment by aclist** [comment]
Looks like mbin also has its own collapse icons, though they function a bit differently. So we'll need to load custom CSS for mbin that hides those icons and moves the vote button. I guess people might still prefer to use one type of collapsible comments over the other, so this is better than just disabling it outright.

**Comment by aclist** [comment]
Staged for release in https://github.com/aclist/kbin-kes/pull/272

**Comment by Pamasich** [comment]
> > @aclist I just noticed another incompatibility.
> > With `Collapsible Comments` turned on, it seems like the vote buttons are getting displaced for me on mbin. Might have to do with recent changes to the mod, or maybe mbin. I've seen the issue on kbin.run and fedia.io.
> > They seem to be moved to the end of comment chains and way pushed to the right.
> 
> Thankfully, it looks like an easy fix. The mod CSS defines a grid template area and refers to the vote section by the classname `vote`, but it should be `aside` on mbin, and this fixes it instantly. I can't cross-check this on kbin.social at the moment, because it's down, but looks either the new CSS can be used for both, or we load alternate stylesheets depending on the instance type.
> 
> As for the OP label, seems mbin adds its own OP label, so this mod should be disabled on there.

So, I've noticed that on my own profile page, the issue still occurs *on kbin* with the latest version of the testing branch.

I've checked the code, and looks like kbin uses `aside` on my own page and `vote` on others.

**Comment by aclist** [comment]
Yes, notifications go out for closed tickets. Created ticket #280
