### ISSUE TITLE
[BUG] Move federation warning to sidebar doesn't work on All Content

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#275]
**Describe the bug**
On the All Content view, the federation alert remains unaffected.

**To Reproduce**
1. Make sure the `Move federation warning to sidebar` mod is turned on.
2. Go to https://kbin.social/*/m/world@lemmy.world
3. The federation warning will remain in its original location

**Expected behavior**
The warning is moved to the sidebar or hidden, depending on the selected option.

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/18553452/2c923aa0-18ab-42e5-bbce-280a8f98fecf)

**Comment by aclist** [comment]
Resolved
