### ISSUE TITLE
[BUG] Double instance name in the sidebar

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#277]
**Describe the bug**
I noticed that magazines in the `Related Magazines` section have their instance suffix duplicated.

![image](https://github.com/aclist/kbin-kes/assets/18553452/f2f08cee-a036-404f-99d0-7a2c766f0f47)

The HTML of the above is:

```
<a href="/m/wowthislemmyexists@lemmy.ca" class="magazine-inline stretched-link instance" title="@wowthislemmyexists@lemmy.ca">
    <img width="30" height="30" style="max-width: 30px; max-height: 30px;" src="https://kbin.social/media/cache/resolve/avatar_thumb/22/14/22146d686a52e4c53e53c189ad65ffc2237b54d189f9f85e2399cadf80ed5e77.png" alt="wowthislemmyexists@lemmy.ca avatar">
    wowthislemmyexists@lemmy.ca<span class="mag-instance">@lemmy.ca</span>
</a>
```

It seems to me that the instance is already added natively by kbin and so the `mag-instance` shouldn't be created.

**KES version:**
- Latest

**Comment by aclist** [comment]
Resolved by [02440f3](https://github.com/aclist/kbin-kes/commit/02440f3d159360ed9dfbceddc601914b0f7ad2ec)
