### ISSUE TITLE
[BUG] Mbin incompatibility with federation awareness

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#278]
Just saw this bug while working on mbin support for default_sort. Haven't looked more into it.

![image](https://github.com/aclist/kbin-kes/assets/18553452/ee79be79-fd4a-4291-971f-a5fd1e692d7f)

![image](https://github.com/aclist/kbin-kes/assets/18553452/8c298625-4a5d-4ee0-a326-a0fdf45669ee)

[It's this thread](https://kbin.run/m/games@lemmy.world/t/353549/Discord-Shuts-Down-Servers-for-Switch-Emulators-Suyu-and-Sudachi-Disables#comments)

**Comment by aclist** [comment]
Resolved by [02440f3](https://github.com/aclist/kbin-kes/commit/02440f3d159360ed9dfbceddc601914b0f7ad2ec)
