### ISSUE TITLE
[BUG] collapse_pins is hiding pins on profiles

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#293]
If you look at [my kbin profile](https://kbin.social/u/Pamasich), you'll notice there's the pins hidden message at the top. That's because I commented on a pinned post, and the mod is catching on to the pinned thread listed in my overview.

![image](https://github.com/aclist/kbin-kes/assets/18553452/6c570f60-fb89-42d3-847b-ba678f5cf76c)

![image](https://github.com/aclist/kbin-kes/assets/18553452/bee4a4ce-570f-4cc8-85c0-fa23955430af)

I assume that's not intended behavior.

**Comment by aclist** [comment]
Resolved
