### ISSUE TITLE
[BUG] Installation Broken Due to Dependency on kbin.social

### ISSUE THREAD

**Issue by wagesj45** [aclist/kbin-kes#298]
**Describe the bug**
Installing the user script using Greasemonkey from the [link in the documentation](https://aclist.github.io/kes/kes.html) fails with a `503` HTTP error. The installation script seems to have a dependency on kbin.social to install.

**To Reproduce**
1. Go to the [KES documenation](https://aclist.github.io/kes/kes.html).
2. Click on "[the install link](https://raw.githubusercontent.com/aclist/kbin-kes/main/kes.user.js)".
3. Wait for the Greasemonkey extension to unlock the "Install" button.

```plaintext
User script download failed

    503 - at https://kbin.social/favicon.svg
```

**Expected behavior**
I'd expect to be able to install the script.

**Screenshots**
![image](https://github.com/user-attachments/assets/d8088778-e241-4f32-89e5-ce2fff2ca01b)

**KES version:**
- Version number: 4.2

**Extension and version:**
- Extension: GreaseMonkey
- Version number: 4.12

**Desktop (please complete the following information):**
 - OS: Spiral Linux (KDE) 
 - Browser: Firefox
 - Browser version: 128.0.3

**Comment by aclist** [comment]
Thank you for the report. I have issued a fix that removes this dependency. Can you check and see if this clears the blockage when installing?

There are some legacy parts of the script that assumed the existence of kbin.social. These will start to be scrubbed in the coming days, and a new magazine/community will likely be created on a difference instance as a place to centralize KES-related information.

As a matter of convenience, current functionality going forward is being tested against the kbin.run and fedia.io instances, but is not dependent on a specific instance.

**Comment by wagesj45** [comment]
Looks like that worked. Thanks for the quick response!

**Comment by aclist** [comment]
Thanks for confirming, and sorry for the inconvenience.
