### ISSUE TITLE
[FEAT] Button to clear and reset all settings

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#61]
- Button in footer
- Trigger a confirm dialog and ask for double confirmation ("This will reset all KES settings and toggle all add-ons to the initial state of OFF. Proceed?")
- Flush localStorage contents of: `kes-settings` and all keys under `json[].namespace`
- Reload the page
- Not sure if placement of button is hideous

@artillect needs button CSS and element aligned in footer

![a](https://github.com/aclist/kbin-kes/assets/92275929/66bf2f83-dd4f-4378-8cbd-ee13b6e8a8d0)

**Comment by Oricul** [comment]
Is there a branch for this outside of `testing`? I'd like to dig into it.

**Comment by aclist** [comment]
It's just a basic visual mocked in dev tools in 30 seconds with a fontawesome icon. All we really need is: `confirm()` dialog, which on true flushes localStorage of the above items: `kes-settings`, and iterate over all of the namespaces enumerated in `json[].namespace`, and flush those as well, using `localStorage.removeItem()`, then `window.location.reload`

I left it as a stub here because positioning elements in CSS is not my fave.

**Comment by aclist** [comment]
Added in 20c5e1efdff6307613a4f347274f32b051f365eb

`.kes-reset-button` needs help with styling, probably needs to be wrapped in another element for proper centering.

**Comment by aclist** [comment]
Resolved by a73f20efdc19f1bfcdb5e29cfcc998bb3a8251ac
