### ISSUE TITLE
[BUG] KES doesn't load properly in Violentmonkey

### ISSUE THREAD

**Issue by artillect** [aclist/kbin-kes#63]
**Describe the bug**
After installing KES with Violentmonkey, it throws a syntax error in the console, and it doesn't load at all. Removing the offending `await` on line 133 allows the script to load, but none of the options appear in the settings

**To Reproduce**
1. Install KES with Violentmonkey
2. Open any kbin instance
3. Check the console for errors

**Expected behavior**
It should load the settings menu properly and show all of the options

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/8906201/72a0c27c-2960-43c1-ad70-ef3aa0362a4a)

**KES version:**
- 1.1.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Browser version: 114.0.2

**Comment by aclist** [comment]
Resolved by 8c716b1c5946a8af4c20dccf1014924648a19ffd
