### ISSUE TITLE
[FEAT] Multiple Author Support

### ISSUE THREAD

**Issue by Oricul** [aclist/kbin-kes#66]
**Is your feature request related to a problem? Please describe.**
Some scripts may have multiple authors, or be abandoned and picked up by someone else.

**Describe the solution you'd like**
Support an author array in manifest.

**Describe alternatives you've considered**
I've thought about the description field, but it would make things too bulky for users I think.

**Additional context**
![Example](https://files.catbox.moe/qfn7vd.png)

**Comment by aclist** [comment]
Sounds great and easy to implement, agree that we shouldn't be stuffing the description field too much
