### ISSUE TITLE
[BUG] "Hide reputation" doesn't hide points on profile pop-ups

### ISSUE THREAD

**Issue by honkaiimpact3rd** [aclist/kbin-kes#77]
**Describe the bug**
While the setting does hide reputation points on profile pages, they are still visible on profile pop-ups.

**To Reproduce**
1. Enable "Hide reputation"
2. Hover over any profile

**Expected behavior**
Reputation points to be hidden

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/107812489/414b1cbd-f4bd-4131-9267-ac30996f054b)

**KES version:**
- Version number 1.1.4

**Comment by aclist** [comment]
Thanks for the report. Should be fixed in `1.1.6`.

Resolved by bed1f7bd01d16fb4246f2ac952e314051e6e864b
