### ISSUE TITLE
[BUG] Collapsible Comments + Federation Awareness (Bubble) = Broken Thread Comments

### ISSUE THREAD

**Issue by Oricul** [aclist/kbin-kes#88]
**Describe the bug**
When collapsible comments is enabled, child comments are not displayed and appear to break the rest of the page.

**To Reproduce**
1. Enable 'Collapsible comments' and _(not sure if this makes a difference)_ toggle 'Collapse by clicking: On headers and bars only'.
2. Browse a thread with comments and child comments.

**Expected behavior**
Child comments should be displayed normally until collapsed.

**Screenshots**
[Video Example](https://files.catbox.moe/mf3h4w.mp4)

**KES version:**
- 2.0.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: LibreWolf (Firefox)
 - Browser version: 115.0.1-1

**Comment by Oricul** [comment]
May have jumped too quickly on this. It appears to break with **federation awareness** enabled.

**Comment by Oricul** [comment]
Seems that the issue lies with federation-awareness' css selector.

**Comment by aclist** [comment]
Resolved by https://github.com/aclist/kbin-kes/pull/89
